
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-13
owner: ucsb-cs156-s25
repo_name: team01-s25-13
pull_requests: [{"author":{"id":"U_kgDOCI505Q","is_bot":false,"login":"chengcxi","name":""},"headRefName":"Cheng-HelpRequest","number":65,"title":"Cheng help request","url":"https://github.com/ucsb-cs156-s25/team01-s25-13/pull/65"},{"author":{"id":"U_kgDOCM8Qxw","is_bot":false,"login":"k-nn-tht","name":"Kenneth Tan"},"headRefName":"Kenneth-RecommendationRequest-getbbyid","number":64,"title":"Kenneth recommendation request getbbyid","url":"https://github.com/ucsb-cs156-s25/team01-s25-13/pull/64"}]
