
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-13
owner: ucsb-cs156-s25
repo_name: team01-s25-13
pull_requests: [{"author":{"id":"MDQ6VXNlcjMwNDIwNTE0","is_bot":false,"login":"nikunjparasar","name":"Nikunj Parasar"},"headRefName":"put-for-menuitem-table","number":63,"title":"add PUT for UCSBDiningCommonsMenuItem controller","url":"https://github.com/ucsb-cs156-s25/team01-s25-13/pull/63"},{"author":{"id":"MDQ6VXNlcjMwNDIwNTE0","is_bot":false,"login":"nikunjparasar","name":"Nikunj Parasar"},"headRefName":"menuitems-get-by-id","number":62,"title":"Nikunj -add GET by id for UCSBDiningCommonsMenuItems","url":"https://github.com/ucsb-cs156-s25/team01-s25-13/pull/62"},{"author":{"id":"U_kgDOCM8Qxw","is_bot":false,"login":"k-nn-tht","name":"Kenneth Tan"},"headRefName":"Kenneth-RecommendationRequest-Controller","number":61,"title":"Recommendation Request Controller","url":"https://github.com/ucsb-cs156-s25/team01-s25-13/pull/61"},{"author":{"id":"MDQ6VXNlcjY1MDUwMDUz","is_bot":false,"login":"connersiou","name":""},"headRefName":"Conner-UCSBOrganization-create-controller","number":60,"title":"Conner - Create UCSBOrganization controller, add GET /all and POST methods","url":"https://github.com/ucsb-cs156-s25/team01-s25-13/pull/60"},{"author":{"id":"MDQ6VXNlcjMwNDIwNTE0","is_bot":false,"login":"nikunjparasar","name":"Nikunj Parasar"},"headRefName":"nikunj-create-menuitem-controller","number":59,"title":"nikunj - create UCSBDiningCommonsMenuItems Controller","url":"https://github.com/ucsb-cs156-s25/team01-s25-13/pull/59"}]
