
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-13
owner: ucsb-cs156-s25
repo_name: team01-s25-13
pull_requests: [{"author":{"id":"U_kgDOCM7m-A","is_bot":false,"login":"timothytwu","name":""},"headRefName":"timothy-put-for-menuitemsreview","number":55,"title":"Timothy - put for menuitemsreview","url":"https://github.com/ucsb-cs156-s25/team01-s25-13/pull/55"},{"author":{"id":"U_kgDOCM7m-A","is_bot":false,"login":"timothytwu","name":""},"headRefName":"timothy-menuitemreviews-get-by-id","number":54,"title":"Timothy - get by ID for menuItemReviews","url":"https://github.com/ucsb-cs156-s25/team01-s25-13/pull/54"},{"author":{"id":"MDQ6VXNlcjY1MDUwMDUz","is_bot":false,"login":"connersiou","name":""},"headRefName":"Conner-UCSBOrganization-create-db","number":53,"title":"Conner - create database table for UCSBOrganization","url":"https://github.com/ucsb-cs156-s25/team01-s25-13/pull/53"},{"author":{"id":"U_kgDOCM7m-A","is_bot":false,"login":"timothytwu","name":""},"headRefName":"timothy-create-menuitemreview-controller","number":52,"title":"Timothy - create MenuItemReview controller, add GET (index) and POST (create)","url":"https://github.com/ucsb-cs156-s25/team01-s25-13/pull/52"},{"author":{"id":"MDQ6VXNlcjU0NzIwMjg2","is_bot":false,"login":"Leexe","name":"Tuan Le"},"headRefName":"Tuan-Article-deleteEndpoint","number":51,"title":"Tuan - article DELETE endpoint","url":"https://github.com/ucsb-cs156-s25/team01-s25-13/pull/51"},{"author":{"id":"MDQ6VXNlcjU0NzIwMjg2","is_bot":false,"login":"Leexe","name":"Tuan Le"},"headRefName":"Tuan-Articles-putEndpoint","number":50,"title":"Tuan - articles PUT endpoint","url":"https://github.com/ucsb-cs156-s25/team01-s25-13/pull/50"},{"author":{"id":"MDQ6VXNlcjU0NzIwMjg2","is_bot":false,"login":"Leexe","name":"Tuan Le"},"headRefName":"Tuan-Articles-getEndpoint","number":49,"title":"Tuan - articles GET endpoint","url":"https://github.com/ucsb-cs156-s25/team01-s25-13/pull/49"},{"author":{"id":"MDQ6VXNlcjU0NzIwMjg2","is_bot":false,"login":"Leexe","name":"Tuan Le"},"headRefName":"Tuan-Articles-createController","number":48,"title":"Tuan - articles create controller","url":"https://github.com/ucsb-cs156-s25/team01-s25-13/pull/48"}]
